spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://182.254.208.159/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /sell
logging:
  level:
    com.fanye.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml